### ISSUE TITLE
Extend the /events Endpoint: retrieve multiple events

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-api#12]
We'll use the events Enpoint to retrieve the events for displaying it on CARTO DB. 

We need to be able to filter for (at least) the following optional parameters: 
- guardian_id, 
- site_id, 
- after_measured_at (from the audio file),
- after_begins_analysis_at,
- classification_analysis, 
- start (number of results to skip), 
- limit (maximum allowed: 500), 

We use GET query parameters to set those params. We always LIMIT the number of returned events to at most 500. 

We return 
{
   limit: 500,
   number_of_results: 6023,
   start: 0, 
   results: [...]
}

The results return the same data as /event:id endpoint.

**Comment by rassokhin-s** [comment]
I've updated some names of attributes. Final list is:
- guardian_**gu**id,
- site_**gu**id,
- after_measured_at,
- after_begins**_at**_analysis,
- classification_analysis,
- **offset** (number of results to skip),
- limit,
