### ISSUE TITLE
Classificator: Delete the "Are you enjoying... " Popup

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-api#15]
Longterm empirical data collection suggests a strong correlation between the "Are you enjoying ..." popup and complete&utter frustration. Therefore, we should delete that popup.

**Comment by rassokhin-s** [comment]
I've removed the popup and changed front-end logic to save confidence with value `0.5` if user has set it to 1 and played window more then 4 times.
@daebwae If I don't need to change confidence to 0.5 in my code, just let me know and I'll remove that code.
